services:
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: ui
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - api

  api:
    build:
      context: ./api
      dockerfile: src/LeagueLeaders.API/Dockerfile
    container_name: api
    ports:
      - "5000:8080"
    networks:
      - app-network
    depends_on:
      - mssql

  mssql:
    container_name: mssql-db
    hostname: mssql-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'Admin@123'
      MSSQL_DATA_DIR: /var/opt/mssql/data
      MSSQL_PID: 'Developer' 
      MSSQL_TCP_PORT: 1433 
    ports: 
      - "1433:1433"
    networks:
      - app-network
    volumes:
      - ./api/data:/var/opt/mssql/data
      - ./api/log:/var/opt/mssql/log
      - ./api/secrets:/var/opt/mssql/secrets    

networks:
  app-network:
    driver: bridge